context:
  version: "8.0.2"

package:
  name: fastify-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/fastify-cli/-/fastify-cli-${{ version }}.tgz
  sha256: 1bde6fd8a64074dfe10d5a1e9d15402305fe36d5a4bd584cd5ae1ff204023b6f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - fastify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run a fastify route with one command!
  homepage: https://github.com/fastify/fastify-cli
  repository: https://github.com/fastify/fastify-cli

extra:
  recipe-maintainers:
    - danielnachun
