context:
  version: "8.0.1"

package:
  name: fastify-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/fastify-cli/-/fastify-cli-${{ version }}.tgz
  sha256: d548e1d003e6c9a77f7e8c80725bf5d1889b4ab3ec2c0aa0fb091520d9abde28

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - fastify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run a fastify route with one command!
  homepage: https://github.com/fastify/fastify-cli
  repository: https://github.com/fastify/fastify-cli

extra:
  recipe-maintainers:
    - danielnachun
