context:
  version: "7.4.0"

package:
  name: fastify-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/fastify-cli/-/fastify-cli-${{ version }}.tgz
  sha256: 4edfe6f47dcf9588c48d9ec7767c9832ffcda0e6e2ded730a44bd6fcdce73766

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - fastify --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run a fastify route with one command!
  homepage: https://github.com/fastify/fastify-cli
  repository: https://github.com/fastify/fastify-cli

extra:
  recipe-maintainers:
    - danielnachun
